Models/Ingredient.cs
using System.Collections.Generic;

namespace SandwichBucket.Models
{
  public class Ingredient
  {
    public Ingredient()
    {
      Sandwiches = new HashSet<SandwichIngredient> {};
      Tags = new HashSet<IngredientTag> {};
    }

    public int IngredientId { get; set; }

    public string Name { get; set; }
    public string Description { get; set; }
   
    public virtual ICollection<SandwichIngredient> Sandwiches { get; }
    public virtual ICollection<IngredientTag> Tags { get; }
  }
}

Controllers/IngredientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using SandwichBucket.Models;
using SandwichBucket.ViewModels;

namespace SandwichBucket.Controllers
{
  public class IngredientsController : Controller
  {
    private readonly SandwichBucketContext _db;

    public IngredientsController(SandwichBucketContext db)
    {
        _db = db;
    }

    // Index
    public ActionResult Index()
    {
      List<Ingredient> Ingredients = _db.Ingredients.ToList();
      return View(Ingredients);
    }

    // GET Create
    public ActionResult Create()
    {
      ViewBag.Sandwiches = _db.Sandwiches.ToList();
      ViewBag.Tags = _db.Tags.ToList();
      return View();
    }

    // POST Create
    [HttpPost]
    public ActionResult Create(Ingredient ingredient, int[] TagId, int[] SandwichId)
    {
      _db.Ingredients.Add(ingredient);
      _db.SaveChanges();

      foreach (int t in TagId)
      {
        _db.IngredientsTags.Add(new IngredientTag() {
          IngredientId = ingredient.IngredientId,
          TagId = t
        });
      }

      foreach (int s in SandwichId)
      {
        _db.SandwichesIngredients.Add(new SandwichIngredient() {
          IngredientId = ingredient.IngredientId,
          SandwichId = s
        });
      }
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    // GET Details
    public ActionResult Details(int id)
    {
      var model = _db.Ingredients.FirstOrDefault(i => i.IngredientId == id);
      return View(model);
    }

    // GET Edit
    public ActionResult Edit(int id)
    {
      var model = _db.Ingredients.FirstOrDefault(i => i.IngredientId == id);
      ViewBag.Sandwiches = _db.Sandwiches.ToList();
      ViewBag.Tags = _db.Tags.ToList();
      ViewBag.SandwichesIngredients = _db.SandwichesIngredients
          .Where(i => i.IngredientId == id)
          .Select(s => s.SandwichId)
          .ToList();
      ViewBag.IngredientsTags = _db.IngredientsTags
          .Where(i => i.IngredientId == id)
          .Select(t => t.TagId)
          .ToList();

      return View(model);
    }

    // POST Edit
    [HttpPost]
    public ActionResult Edit(Ingredient ingredient, int[] TagId, int[] SandwichId)
    {
      _db.IngredientsTags
          .Where(i => i.IngredientId == ingredient.IngredientId && !TagId.Contains(i.TagId))
          .ToList()
          .ForEach(r => _db.IngredientsTags.Remove(r));
      _db.SandwichesIngredients
          .Where(i => i.IngredientId == ingredient.IngredientId && !SandwichId.Contains(i.SandwichId))
          .ToList()
          .ForEach(r => _db.SandwichesIngredients.Remove(r));

      foreach (int t in TagId)
      {
        if (_db.IngredientsTags.Any(it => it.IngredientId == ingredient.IngredientId && it.TagId == t))
          continue;

        _db.IngredientsTags.Add(new IngredientTag() {
          IngredientId = ingredient.IngredientId,
          TagId = t
        });
      }

      foreach (int s in SandwichId)
      {
        if (_db.SandwichesIngredients.Any(si => si.IngredientId == ingredient.IngredientId && si.SandwichId == s))
          continue;

        _db.SandwichesIngredients.Add(new SandwichIngredient() {
          IngredientId = ingredient.IngredientId,
          SandwichId = s
        });
      }

      _db.Entry(ingredient).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // GET Delete
    public ActionResult Delete(int id)
    {
      var model = _db.Ingredients.FirstOrDefault(i => i.IngredientId == id);
      return View(model);
    }

    // POST DELETE
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var ingredient = _db.Ingredients.FirstOrDefault(i => i.IngredientId == id);
      _db.Ingredients.Remove(ingredient);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Views/Ingredients/Create.cshtml
<h1>Add a new ingredient</h1>

@using (Html.BeginForm())
{
  @await Html.PartialAsync("_Forms/_IngredientForm")
  <br />
  <button style="text-align:center">CHOW TIME</button>
}

Views/Ingredients/Delete.cshtml
@model SandwichBucket.Models.Ingredient

<h1 class="are-you-sure">ARE YOU SURE YOU WANT TO DELETE THIS?</h1>

<h1>@Model.Name</h1>

<h4>Description: @Model.Description</h4>

@if (Model.Sandwiches.Count != 0)
{
  <h2>Sandwiches</h2>
  <ul>
  @foreach (var s in Model.Sandwiches.Select(s => s.Sandwich).ToList())
  {
    <li>@s.Name / @s.Description</li>
  }
  </ul>
}

@if (Model.Tags.Count != 0)
{
  <hr />
  <h2>Tags</h2>
  <ul>
  @foreach (var t in Model.Tags.Select(t => t.Tag).ToList())
  {
    <li>@t.Name</li>
  }
  </ul>
}
<br />
@using (Html.BeginForm())
{
  <button class="delete-button">MAKE SURE YOU'RE SURE BEFORE YOU HIT THIS BUTTON</button>
}

Views/Ingredients/Details.cshtml
@model SandwichBucket.Models.Ingredient

<h1>@Model.Name</h1>

<h4>Description: @Model.Description</h4>

@if (Model.Sandwiches.Count != 0)
{
  <h2>Sandwiches</h2>
  <ul>
  @foreach (var s in Model.Sandwiches.Select(x => x.Sandwich).ToList())
  {
    <li>@s.Name / @s.Description</li>
  }
  </ul>
}

@if (Model.Tags.Count != 0)
{
  <hr />
  <h2>Tags</h2>
  <ul>
  @foreach (var t in Model.Tags.Select(t => t.Tag).ToList())
  {
    <li>@t.Name</li>
  }
  </ul>
}

<a href="/Ingredients/Edit/@Model.IngredientId"><button type=button>PUT A LITTLE HEAT IN THIS MEAT</button></a>
<a href="/Ingredients/Delete/@Model.IngredientId"><button type=button>I THINK THIS LETTUCE HAS GOT TO GO</button></a>

Views/Ingredients/Edit.cshtml
@model SandwichBucket.Models.Ingredient

<h1>Edit @Model.Name</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(i => i.IngredientId)

  @await Html.PartialAsync("_Forms/_IngredientForm")
  <br />
  <button>FIX THIS PIECE OF CRAP</button>
}

Views/Ingredients/Index.cshtml
@model List<Ingredient>

<h1>Ingredients</h1>

@if (@Model.Count == 0)
{
  <h3>No Ingredients</h3>
  <img src="/img/baby.gif" />
}
else
{
  <table>
      @foreach (Ingredient i in Model)
      {
            <tr>
              <td class="ing"><span class="stylized">@i.Name</span>
                <br />@i.Description
                <br />@Html.ActionLink("Check It Out", "Details", "Ingredients", new { id = i.IngredientId })
              </td>
            </tr>
      }
  </table>
}

<a href="/Ingredients/Create"><button type=button>MAKE YOURSELF UP ONE</button></a>