Models/Sandwich.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SandwichBucket.Models
{
  public class Sandwich
  {
    public Sandwich()
    {
      Ingredients = new HashSet<SandwichIngredient> {};
      Tags = new HashSet<SandwichTag> {};
    }

    public int SandwichId { get; set; }

    public string Name { get; set; }
    public string Description { get; set; }
    public SandwichAlignment Alignment { get; set; }

    public virtual ICollection<SandwichIngredient> Ingredients { get; }
    public virtual ICollection<SandwichTag> Tags { get; }
  }

  public enum SandwichAlignment
  {
    [Display(Name = "Lawful Good")]
    LawfulGood,
    [Display(Name = "Neutral Good")]
    NeutralGood,
    [Display(Name = "Chaotic Good")]
    ChaoticGood,
    [Display(Name = "Lawful Neutral")]
    LawfulNeutral,
    [Display(Name = "True Neutral")]
    TrueNeutral,
    [Display(Name = "Chaotic Neutral")]
    ChaoticNeutral,
    [Display(Name = "Lawful Evil")]
    LawfulEvil,
    [Display(Name = "Neutral Evil")]
    NeutralEvil,
    [Display(Name = "Chaotic Evil")]
    ChaoticEvil
  }

  // How could we represent a sandwich on a political compass?
  // What would be a sandwiches Meyers-Briggs type?
}

Controllers/SandwichesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using SandwichBucket.Models;
using SandwichBucket.ViewModels;

namespace SandwichBucket.Controllers
{
  public class SandwichesController : Controller
  {
    private readonly SandwichBucketContext _db;

    public SandwichesController(SandwichBucketContext db)
    {
        _db = db;
    }

    // Index
    public ActionResult Index()
    {
      List<Sandwich> Sandwiches = _db.Sandwiches.ToList();
      return View(Sandwiches);
    }

    // GET Create
    public ActionResult Create()
    {
      ViewBag.Ingredients = _db.Ingredients.ToList();
      ViewBag.Tags = _db.Tags.ToList();

      return View();
    }

    // POST Create
    [HttpPost]
    public ActionResult Create(Sandwich sandwich, int[] TagId, int[] IngredientId)
    {
      _db.Sandwiches.Add(sandwich);
      _db.SaveChanges();

      foreach (int t in TagId)
      {
        _db.SandwichesTags.Add(new SandwichTag() {
          TagId = t,
          SandwichId = sandwich.SandwichId
        });
      }

      foreach (int i in IngredientId)
      {
        _db.SandwichesIngredients.Add(new SandwichIngredient() {
          IngredientId = i,
          SandwichId = sandwich.SandwichId
        });
      }
      _db.SaveChanges();

      return RedirectToAction("Index");
    }

    // GET Details
    public ActionResult Details(int id)
    {
      var model = _db.Sandwiches.FirstOrDefault(s => s.SandwichId == id);
      return View(model);
    }

    // GET Edit
    public ActionResult Edit(int id)
    {
      var model = _db.Sandwiches.FirstOrDefault(s => s.SandwichId == id);
      ViewBag.Ingredients = _db.Ingredients.ToList();
      ViewBag.Tags = _db.Tags.ToList();
      ViewBag.SandwichesIngredients = _db.SandwichesIngredients
          .Where(s => s.SandwichId == id)
          .Select(i => i.IngredientId)
          .ToList();
      ViewBag.SandwichesTags = _db.SandwichesTags
          .Where(s => s.SandwichId == id)
          .Select(t => t.TagId)
          .ToList();
      // var model = new SandwichEditViewModel() {
      //   Sandwich = _db.Sandwiches.FirstOrDefault(s => s.SandwichId == id),
      //   Ingredients = _db.Ingredients.ToList(),
      //   Tags = _db.Tags.ToList()
      // };

      return View(model);
    }

    // Before Edit
    // 1 => 0, 2, 4
    // After Edit
    // 1 => 1, 2, 4, 6 (Removed 0, and Added 1, 6)
    // 2nd Edit
    // 1 => 0, 2, 4 (Added 0, Removed 1, 6)

    // SandwichId=2
    // &Name=Banh+Mi
    // &Description=Hell+yes
    // &Alignment=LawfulEvil
    // &IngredientId=1
    // &IngredientId=2
    // &IngredientId=4
    // &IngredientId=6
    // &IngredientId=17
    // &IngredientId=28
    // &IngredientId=33
    // &IngredientId=43
    // &IngredientId=54
    // &IngredientId=65
    // &IngredientId=118
    // &IngredientId=119&

    // POST Edit
    [HttpPost]
    public ActionResult Edit(Sandwich sandwich, int[] TagId, int[] IngredientId)
    {
      // If this relationship existed before the Edit and doesn't exist at this point
      // I need to remove it
      _db.SandwichesTags
          .Where(s => s.SandwichId == sandwich.SandwichId && !TagId.Contains(s.TagId))
          .ToList()
          .ForEach(r => _db.SandwichesTags.Remove(r));
      _db.SandwichesIngredients
          .Where(s => s.SandwichId == sandwich.SandwichId && !IngredientId.Contains(s.IngredientId))
          .ToList()
          .ForEach(r => _db.SandwichesIngredients.Remove(r));

      // If this relationship doesn't already exist at this point, I need to create it
      foreach (int t in TagId)
      {
        if (_db.SandwichesTags.Any(st => st.SandwichId == sandwich.SandwichId && st.TagId == t))
          continue;

        _db.SandwichesTags.Add(new SandwichTag() {
          SandwichId = sandwich.SandwichId,
          TagId = t
        });
      }

      foreach (int i in IngredientId)
      {
        if (_db.SandwichesIngredients.Any(si => si.SandwichId == sandwich.SandwichId && si.SandwichId == i))
          continue;

        _db.SandwichesIngredients.Add(new SandwichIngredient() {
          SandwichId = sandwich.SandwichId,
          IngredientId = i
        });
      }

      _db.Entry(sandwich).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // GET Delete
    public ActionResult Delete(int id)
    {
      var model = _db.Sandwiches.FirstOrDefault(s => s.SandwichId == id);
      return View(model);
    }

    // POST DELETE
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var sandwich = _db.Sandwiches.FirstOrDefault(s => s.SandwichId == id);
      _db.Sandwiches.Remove(sandwich);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public async Task<ActionResult<Object>> Random()
    {
      var sandwichCount = await _db.Sandwiches.CountAsync();
      var sandwich = await _db.Sandwiches
              .Skip(new Random().Next(sandwichCount))
              .FirstOrDefaultAsync();
      
      return Json(new {
        Name = sandwich.Name,
        Description = sandwich.Description,
        Alignment = sandwich.Alignment,
        SandwichId = sandwich.SandwichId
      });
    }
  }
}

Views/Sandwiches/Create.cshtml
<h1>Create a new sandwich</h1>

@using (Html.BeginForm())
{
  @await Html.PartialAsync("_Forms/_SandwichForm")
  <br />
  <button style="text-align:center">~*~ MAKE IT SO ~*~</button>
}

Views/Sandwiches/Delete.cshtml
@model SandwichBucket.Models.Sandwich

<h1 class="are-you-sure">ARE YOU SURE YOU WANT TO DELETE THIS?</h1>

<h1>@Model.Name</h1>

<h4>Alignment: @Html.DisplayFor(m => m.Alignment)</h4>

<h4>Description: @Model.Description</h4>

@if (Model.Ingredients.Count != 0)
{
  <h2>Ingredients</h2>
  <ul>
  @foreach (var i in Model.Ingredients.Select(i => i.Ingredient).ToList())
  {
    <li>@i.Name / @i.Description</li>
  }
  </ul>
}

@if (Model.Tags.Count != 0)
{
  <hr />
  <h2>Tags</h2>
  <ul>
  @foreach (var t in Model.Tags.Select(t => t.Tag).ToList())
  {
    <li>@t.Name</li>
  }
  </ul>
}
<br />
@using (Html.BeginForm())
{
  <button class="delete-button">MAKE SURE YOU'RE SURE BEFORE YOU HIT THIS BUTTON</button>
}

Views/Sandwiches/Details.cshtml
@model SandwichBucket.Models.Sandwich

<h1>@Model.Name</h1>

<h4>Alignment: @Html.DisplayFor(m => m.Alignment)</h4>

<h4>Description: @Model.Description</h4>

@if (Model.Ingredients.Count != 0)
{
  <h2>Ingredients</h2>
  <ul>
  @foreach (var i in Model.Ingredients.Select(i => i.Ingredient).ToList())
  {
    <li>@i.Name / @i.Description</li>
  }
  </ul>
}

@if (Model.Tags.Count != 0)
{
  <hr />
  <h2>Tags</h2>
  <ul>
  @foreach (var t in Model.Tags.Select(t => t.Tag).ToList())
  {
    <li>@t.Name</li>
  }
  </ul>
}

<a href="/Sandwiches/Edit/@Model.SandwichId"><button type=button>PUT A LITTLE PERFUME ON THIS PIG</button></a>
<a href="/Sandwiches/Delete/@Model.SandwichId"><button type=button>THROW THIS PIECE OF TRASH IN THE GARBAGE</button></a>

Views/Sandwiches/Edit.cshtml
@model SandwichBucket.Models.Sandwich

<h1>Edit @Model.Name</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(s => s.SandwichId)

  @await Html.PartialAsync("_Forms/_SandwichForm")
  <br />
  <button>FIX THIS PIECE OF CRAP</button>
}

Views/Sandwiches/Index.cshtml
@model List<Sandwich>

<h1>Sandwiches</h1>

@if (@Model.Count == 0)
{
  <h3>No Sandwiches</h3>
  <img src="/img/baby.gif" />
}
else
{
  @foreach (Sandwich s in Model)
  {
    
      <ul class="sandlist">
        <li><span class="stylized">@s.Name</span>
          <br />@s.Description
          <br />@Html.ActionLink("Check It Out", "Details", "Sandwiches", new { id = s.SandwichId })
        </li>
      </ul>
    
  }
}

<a href="/Sandwiches/Create"><button type=button>MAKE YOURSELF UP ONE</button></a>