Models/Tag.cs
using System.Collections.Generic;

namespace SandwichBucket.Models
{
  public class Tag
  {
    public Tag()
    {
      Sandwiches = new HashSet<SandwichTag> {};
      Ingredients = new HashSet<IngredientTag> {};
    }

    public int TagId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<SandwichTag> Sandwiches { get; }
    public virtual ICollection<IngredientTag> Ingredients { get; }
  }
}

Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using SandwichBucket.Models;
using SandwichBucket.ViewModels;

namespace SandwichBucket.Controllers
{
  public class TagsController : Controller
  {
    private readonly SandwichBucketContext _db;

    public TagsController(SandwichBucketContext db)
    {
        _db = db;
    }

    // Index
    public ActionResult Index()
    {
      List<Tag> Tags = _db.Tags.ToList();
      return View(Tags);
    }

    // GET Create
    public ActionResult Create()
    {
      return View();
    }

    // POST Create
    [HttpPost]
    public ActionResult Create(Tag tag)
    {
      _db.Tags.Add(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // GET Details
    public ActionResult Details(int id)
    {
      var model = _db.Tags.FirstOrDefault(t => t.TagId == id);
      return View(model);
    }

    // GET Edit
    public ActionResult Edit(int id)
    {
      var model = _db.Tags.FirstOrDefault(t => t.TagId == id);
      return View(model);
    }

    // POST Edit
    [HttpPost]
    public ActionResult Edit(Tag tag)
    {
      _db.Entry(tag).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    // GET Delete
    public ActionResult Delete(int id)
    {
      var model = _db.Tags.FirstOrDefault(t => t.TagId == id);
      return View(model);
    }

    // POST DELETE
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var tag = _db.Tags.FirstOrDefault(t => t.TagId == id);
      _db.Tags.Remove(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Views/Tags/Create.cshtml
<h1>Create a new tag</h1>

@using (Html.BeginForm())
{
  @await Html.PartialAsync("_Forms/_TagForm")
  <br />
  <br />
  <button style="text-align:center">GET 'ER DONE!!!!!!!!</button>
}

Views/Tags/Delete.cshtml
@model SandwichBucket.Models.Tag

<h1 class="are-you-sure">ARE YOU SURE YOU WANT TO DELETE THIS?</h1>

<h1>@Model.Name</h1>

<br />
@using (Html.BeginForm())
{
  <button class="delete-button">MAKE SURE YOU'RE SURE BEFORE YOU HIT THIS BUTTON</button>
}

Views/Tags/Details.cshtml
@model SandwichBucket.Models.Tag

<h1>@Model.Name</h1>

<p>(What else did you expect? It's a tag!)</p>

<a href="/Tags/Edit/@Model.TagId"><button type=button>TAG SOMEONE ELSE IN</button></a>
<a href="/Tags/Delete/@Model.TagId"><button type=button>YOU'RE NO LONGER IT</button></a>

Views/Tags/Edit.cshtml
@model SandwichBucket.Models.Tag

<h1>Create a new tag</h1>

@using (Html.BeginForm())
{
  @Html.HiddenFor(t => t.TagId)
  @await Html.PartialAsync("_Forms/_TagForm")
  <br />
  <br />
  <button style="text-align:center">CHANGE IT UP</button>
}

Views/Tags/Index.cshtml
@model List<Tag>

<h1>Tags</h1>

@if (@Model.Count == 0)
{
  <h3>No Tags</h3>
  <img src="/img/baby.gif" />
}
else
{
  @foreach (Tag t in Model)
  {
    
      <ul>
        <li><span class="stylized">@t.Name</span>
          <br />@Html.ActionLink("Check It Out", "Details", "Tags", new { id = t.TagId })
        </li>
      </ul>
    
  }
}

<a href="/Tags/Create"><button type=button>TAG YOURSELF IN</button></a>